### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by nlacombe42** [nlacombe42/nl-jsonfeed#4]

**Comment by nlacombe42** [comment]
created following ticket in maven central's jira: https://issues.sonatype.org/browse/OSSRH-69269

**Comment by nlacombe42** [comment]
published to the repo. waiting for it to be indexed on https://mvnrepository.com/

**Comment by doches** [comment]
Looks indexed to me; I got here via https://search.maven.org/search?q=jsonfeed -- so that's contributing to #7, too!

**Comment by nlacombe42** [comment]
closing this issue since it's now indexed by maven central

**Comment by nlacombe42** [comment]
btw if you try my library i'd love to hear your feedback on it 🙂

**Comment by doches** [comment]
Sadly, I ended up rolling my own (well, writing out the JsonFeed schema using Immutables) to avoid having to deal with Jigsaw as Java modules cause me nothing but pain. I couldn't get the Jackson serializer to load (via your `ServiceLoader` usage), despite it being available on the classpath. I'm sure this is my fault, and not yours (again, modules = pain).

**Comment by nlacombe42** [comment]
answered your last comment here: https://github.com/nlacombe42/nl-jsonfeed/issues/9#issuecomment-881724062
